name: plugins
version: 1.0.1
author: samrg472 <samrg472@gmail.com>
description: A simple plugin loading system
homepage: https://github.com/samrg472/plugins.dart
environment:
  sdk: '>=1.5.0'
dependencies:
  path: '>=1.2.1 <2.0.0'
  yaml: '>=2.0.0 <2.2.0'
